### ISSUE TITLE
Error when processing repository

### ISSUE THREAD

**Issue by dgarijo** [SoftwareUnderstanding/code_inspector#149]
I got an error when processing a sample repo:
Command:
```
python code_inspector.py -i ../test_repos/HXL-Data-Science-file-formats
```

Repo: https://github.com/EticaAI/HXL-Data-Science-file-formats/

Error: 
```
raceback (most recent call last):
  File "code_inspector.py", line 785, in <module>
    main()
  File "/home/dgarijo/Documents/GitHub/code_inspector/env/lib/python3.8/site-packages/click/core.py", line 1134, in __call__
    return self.main(*args, **kwargs)
  File "/home/dgarijo/Documents/GitHub/code_inspector/env/lib/python3.8/site-packages/click/core.py", line 1059, in main
    rv = self.invoke(ctx)
  File "/home/dgarijo/Documents/GitHub/code_inspector/env/lib/python3.8/site-packages/click/core.py", line 1401, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dgarijo/Documents/GitHub/code_inspector/env/lib/python3.8/site-packages/click/core.py", line 767, in invoke
    return __callback(*args, **kwargs)
  File "code_inspector.py", line 773, in main
    dir_info["software_invocation"] = software_invocation(dir_info, input_path)
  File "/home/dgarijo/Documents/GitHub/code_inspector/utils.py", line 103, in software_invocation
    software_invocation_info.append(inspect_setup(input_path))
  File "/home/dgarijo/Documents/GitHub/code_inspector/parse_setup_files.py", line 148, in inspect_setup
    with open(os.path.join(abs_parent_dir, "setup.py"), 'r') as setup_fh:
FileNotFoundError: [Errno 2] No such file or directory: '/home/dgarijo/Documents/GitHub/test_repos/HXL-Data-Science-file-formats/setup.py'
```

**Comment by dgarijo** [comment]
Another repo that produces error: 
Repo: https://github.com/yandex-research/rtdl

```
######## Processing: rtdl
Error when applying code_inspector to rtdlb'Traceback (most recent call last):\n  File "code_inspector.py", line 785, in <module>\n    main()\n  File "/home/dgarijo/Documents/GitHub/code_inspector/env/lib/python3.8/site-packages/click/core.py", line 1134, in __call__\n    return self.main(*args, **kwargs)\n  File "/home/dgarijo/Documents/GitHub/code_inspector/env/lib/python3.8/site-packages/click/core.py", line 1059, in main\n    rv = self.invoke(ctx)\n  File "/home/dgarijo/Documents/GitHub/code_inspector/env/lib/python3.8/site-packages/click/core.py", line 1401, in invoke\n    return ctx.invoke(self.callback, **ctx.params)\n  File "/home/dgarijo/Documents/GitHub/code_inspector/env/lib/python3.8/site-packages/click/core.py", line 767, in invoke\n    return __callback(*args, **kwargs)\n  File "code_inspector.py", line 773, in main\n    dir_info["software_invocation"] = software_invocation(dir_info, input_path)\n  File "/home/dgarijo/Documents/GitHub/code_inspector/utils.py", line 103, in software_invocation\n    software_invocation_info.append(inspect_setup(input_path))\n  File "/home/dgarijo/Documents/GitHub/code_inspector/parse_setup_files.py", line 148, in inspect_setup\n    with open(os.path.join(abs_parent_dir, "setup.py"), \'r\') as setup_fh:\nFileNotFoundError: [Errno 2] No such file or directory: \'/home/dgarijo/Documents/GitHub/test_repos/rtdl/setup.py\'\n'
```

**Comment by rosafilgueira** [comment]
Fixed
