### ISSUE TITLE
installation instructions error

### ISSUE THREAD

**Issue by dgarijo** [SoftwareUnderstanding/code_inspector#69]
I have detected this odd behavior (I have not investigated why yet). For Shapely, we obtain:

```
Shapely {'type': 'package', 'installation': 'pip install Failed `CDLL(libgeos_c.so.1)`\nFailed `CDLL(libgeos_c.so)`\nTraceback (most recent call last):\n  File "setup.py", line 74, in <module>\n    from shapely._buildcfg import geos_version_string, geos_version, \\\n  File "/home/dgarijo/Documents/GitHub/test_repos/Shapely/shapely/_buildcfg.py", line 166, in <module>\n    lgeos = load_dll(\'geos_c\',\n  File "/home/dgarijo/Documents/GitHub/test_repos/Shapely/shapely/_buildcfg.py", line 159, in load_dll\n    raise OSError(\nOSError: Could not find library geos_c or load any of its variants [\'libgeos_c.so.1\', \'libgeos_c.so\']', 'run': 'Failed `CDLL(libgeos_c.so.1)`\nFailed `CDLL(libgeos_c.so)`\nTraceback (most recent call last):\n  File "setup.py", line 74, in <module>\n    from shapely._buildcfg import geos_version_string, geos_version, \\\n  File "/home/dgarijo/Documents/GitHub/test_repos/Shapely/shapely/_buildcfg.py", line 166, in <module>\n    lgeos = load_dll(\'geos_c\',\n  File "/home/dgarijo/Documents/GitHub/test_repos/Shapely/shapely/_buildcfg.py", line 159, in load_dll\n    raise OSError(\nOSError: Could not find library geos_c or load any of its variants [\'libgeos_c.so.1\', \'libgeos_c.so\'] --help'}
```
What is this installation error?

**Comment by dgarijo** [comment]
Now when there is an error, the installation and run will not appear.
